year = [
    '2012',
    '2011',
    '2010',
    '2009',
    '2008',
    '2007',
    '2006',
    '2005',
    '2004',
    '2003',
    '2002',
    '2001']

rank_by = [
    'giving',
    'assets',
    'gifts_received']

organization_type = [
    'independent',
    'corporate',
    'community',
    'operating',
    'family']

funder_location = [
    'state:AL',
    'state:AK',
    'state:AZ',
    'state:AR',
    'state:CA',
    'state:CO',
    'state:CT',
    'state:DE',
    'state:DC',
    'state:FL',
    'state:GA',
    'state:HI',
    'state:ID',
    'state:IL',
    'state:IN',
    'state:IA',
    'state:KS',
    'state:KY',
    'state:LA',
    'state:ME',
    'state:MD',
    'state:MA',
    'state:MI',
    'state:MN',
    'state:MS',
    'state:MO',
    'state:MT',
    'state:NE',
    'state:NV',
    'state:NH',
    'state:NJ',
    'state:NM',
    'state:NY',
    'state:NC',
    'state:ND',
    'state:OH',
    'state:OK',
    'state:OR',
    'state:PA',
    'state:RI',
    'state:SC',
    'state:SD',
    'state:TN',
    'state:TX',
    'state:UT',
    'state:VT',
    'state:VA',
    'state:WA',
    'state:WV',
    'state:WI',
    'state:WY']
